version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: spr-postgres
    environment:
      POSTGRES_DB: spr_db
      POSTGRES_USER: spr_user
      POSTGRES_PASSWORD: spr_password_2025
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./ops/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spr_user -d spr_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: