version: '3.8'

services:
  evolution-api:
    image: atendai/evolution-api:latest
    container_name: evolution_api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Database Configuration
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://spr_user:spr_pass@pg:5432/evolution?schema=public
      
      # Redis Configuration
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://redis:6379/6
      - CACHE_REDIS_PREFIX_KEY=evolution_cache
      
      # Server Configuration
      - SERVER_URL=https://evo.royalnegociosagricolas.com.br
      - SERVER_PORT=8080
      - LOG_LEVEL=INFO
      - LOG_COLOR=true
      - LOG_BAILEYS=false
      
      # Webhook Global
      - WEBHOOK_GLOBAL_ENABLED=true
      - WEBHOOK_GLOBAL_URL=https://royalnegociosagricolas.com.br/api/webhook/evolution?token=f542b07048e0b7401bf1de47e84b2822f27391aa414cc72c
      - WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS=true
      
      # API Key Global
      - AUTHENTICATION_API_KEY=c451bb1deb223c150b4c41ed3925bfaa91cdacf45d3d01350b2a16520c97b21c
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true
      
      # Instance Settings
      - CONFIG_SESSION_PHONE_CLIENT=SPR
      - CONFIG_SESSION_PHONE_NAME=Sistema Preditivo Royal
      - QRCODE_LIMIT=15
      
      # Integration Settings
      - INTEGRATION_OPENAI_ENABLED=false
      - INTEGRATION_DIFY_ENABLED=false
      
      # Clean Store
      - CLEAN_STORE_CLEANING_INTERVAL=7200
      - CLEAN_STORE_MESSAGES=true
      - CLEAN_STORE_MESSAGE_UP_TO=false
      - CLEAN_STORE_CONTACTS=true
      - CLEAN_STORE_CHATS=true
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution_net
    depends_on:
      - pg
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/manager/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  pg:
    image: postgres:16-alpine
    container_name: evolution_pg
    restart: unless-stopped
    environment:
      - POSTGRES_DB=evolution
      - POSTGRES_USER=spr_user
      - POSTGRES_PASSWORD=spr_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - evolution_net
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: evolution_redis
    restart: unless-stopped
    command: redis-server --requirepass Ev0lut1on@2024
    volumes:
      - redis_data:/data
    networks:
      - evolution_net
    ports:
      - "6379:6379"

volumes:
  evolution_instances:
  pgdata:
  redis_data:

networks:
  evolution_net:
    driver: bridge
