version: '3.8'

services:
  evolution-api:
    image: atendai/evolution-api:latest
    container_name: evolution_api_simple
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Configuração mínima
      - SERVER_URL=http://localhost:8080
      - AUTHENTICATION_API_KEY=c451bb1deb223c150b4c41ed3925bfaa91cdacf45d3d01350b2a16520c97b21c
      - WEBHOOK_GLOBAL_URL=https://royalnegociosagricolas.com.br/api/webhook/evolution?token=f542b07048e0b7401bf1de47e84b2822f27391aa414cc72c
      - WEBHOOK_GLOBAL_ENABLED=true
      - WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS=true
      # Configurações básicas sem database externo
      - DATABASE_ENABLED=false
      - REDIS_ENABLED=false
      - LOG_LEVEL=INFO
      - LOG_COLOR=true
      - CONFIG_SESSION_PHONE_CLIENT=SPR
      - CONFIG_SESSION_PHONE_NAME=Sistema Preditivo Royal
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution_net

volumes:
  evolution_instances:

networks:
  evolution_net:
    driver: bridge